title: My Blog
description: "Mechanical Engineer" 


url: https://hjahanshiri.github.io
baseurl: ""

email: "example@mail.com"
twitter_username: "twitteruser"
github_username: "githubuser"
linkedin_username: "linkedinuser"

# Build settings
markdown: kramdown

# Collections for your four sections
collections:
  essays:
    output: true
    permalink: /essays/:title/
  log:
    output: true
    permalink: /log/:title/
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "log"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
