title: Noah's Blog
description: Mechanical Engineer • Philosophy • Teaching

email: your-email@example.com


email: "example@mail.com"
twitter_username: "twitteruser"
github_username: "githubuser"
linkedin_username: "linkedinuser"

# Build settings
markdown: kramdown
permalink: /:collection/:title/

# Collections for your four sections
collections:
  essays:
    output: true
    permalink: /essays/:title/
  log:
    output: true
    permalink: /log/:title/
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "log"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
